apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blue-green-svc
  name: blue-green-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blue
  type: NodePort
